### ISSUE TITLE
Return errors from requests?

### ISSUE THREAD

**Issue by countnazgul** [mindspank/qsocks#4]
Is there any reason to not return error messages from the ws requests?

For example:

```javascript
Doc.prototype.createSessionObject = function(Prop) {
    var connection = this.connection;
    return this.connection.ask(this.handle, 'CreateSessionObject', arguments).then(function(msg) {
        return connection.create(msg.qReturn);
    }, function (error) {
        return { error: error };
    });
};
```

And then the error can be fetched outside:

```javascript
activeApp.createSessionObject(obj).then(function(list) {
      if(list.err) {
        // list.error.message --> do something with the error (display msg for example)
      } else {
       // process data
      }
});
```

**Comment by mindspank** [comment]
All methods in qsocks is promises. Promises works through passing them 2 functions, one for when the promise is fulfilled and one for it's when reject. The benefit of this is that they can bubble all the way up to a generic error handler in your promise chain.

```javascript
//createSessionObject().then(fullfilled, rejected)
app.createSessionObject(obj).then(function(handle) {
  // -> fullfilled promise
}, function(error) {
  // -> promise was rejected
});
```

**Comment by mindspank** [comment]
Just as an update to this, the first time when people usually run into errors is due to how QS handles the websocket identities and throws and error during openDoc().

This example helps clear up some confusion around how establish scoped connections
https://github.com/mindspank/qsocks/blob/master/examples/Global/connect-scoped-connections.js
